font_family             JetBrainsMono Nerd Font Mono
font_size               11.0
window_padding_width    5
italic_font             auto
bold_font               auto
bold_italic_font        auto
background_opacity      1
copy_on_select          no
scrollbar               never
confirm_os_window_close 0
include                 theme.conf


map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab

map ctrl+shift+left no_op
map ctrl+shift+right no_op
